### ISSUE TITLE
Add Guild Model

### ISSUE THREAD

**Issue by GabeStah** [GabeStah/vcp#17]
## TODO
- [x] Generate database migration
- [x] Create model
- [x] Create model spec
- [x] Create feature spec
- [x] Create request spec
- [x] Create controller
- [x] Alter Character model to utilize new Guild model association.
## Database

achievement_points:integer
active:boolean - Determines if guild should be part of the current VCP member list
battlegroup:string
level:integer
name:string
primary:boolean - Determines if guild is the default (base) guild for VCP
region:string
realm:string
side:integer
verified:boolean - Determines if the guild has been found on battle.net
